### ISSUE TITLE
Use keepAlive / best effort for event tracking requests

### ISSUE THREAD

**Issue by m-radzikowski** [rehanvdm/serverless-website-analytics-client#19]
Hey,
I'm adding the analytics on a static website (generated with Astro). Each link click is a page reload - like in the old days ;-)

Link click tracking is called in `click` listener right before the page unloads. In most cases, the `analyticsTrack()` request is then visible as `canceled` in network debug tools. On Chrome, the request often actually succeed (I can see it in the backend), but on Safari almost never. Didn't test on Firefox.

Making the requests with fetch `keepalive: true` solves the issue. I see it's already implemented in the [underlying `sendRequest()` function](https://github.com/rehanvdm/serverless-website-analytics-client/blob/4d26d6c38368d2c3328d75904a872de27bb2bd69/package/src/index.ts#L44) as `bestEffort` param.

Could we have a parameter to send tracking events with `bestEffort` flag? Either as a param in `swaClient.v1.analyticsTrack()` or in global options, something like `bestEffortTrackRequests`?

I'm willing to implement it and send a PR if you find it okay.

**Comment by rehanvdm** [comment]
So if I understand correctly. Steps to recreate it being canceled would be:

- Page 1 
- Click on a link that will:
  - Send a tracking event
  - Go to Page 2
- Page 2

So it goes to Page 2 before the tracking event can be sent and you can see it in your browser as being canceled? 

You are correct that the function that sends the request with the `bestEffort` flag is used for Page views only. 

When you open a Page a Post+Keepalive is used, so the `bestEffort` flag is false. Then when leaving the page the flag is true which will try to use Post+Keepalive unless it is FireFox that does not support it, then we use `sendBeacon`. We don't want to always use `sendBeacon` because AdBlockers block them by default if the request isn't for the same domain.

I think adding `bestEffort` as an optional function param for the `analyticsTrack` function, defaulting to `false` sounds reasonable. Then you can just set it to true when using it for this specific use case of tracking events when navigating away from pages.
 
We also need to add it to the stand-alone script here https://github.com/rehanvdm/serverless-website-analytics-client/blob/master/package/src/cdn/client-script.ts#L79 so that it can be passed with an attribute. Maybe calling it `swa-event-best-effort` or maybe `swa-event-async` is better? 

I'm not too married to the naming of `bestEffort` either, so open to suggestions.

I would love a PR, if you get the time the time for it, let me know.

**Comment by m-radzikowski** [comment]
> So it goes to Page 2 before the tracking event can be sent and you can see it in your browser as being canceled?

Exactly.

> I'm not too married to the naming of bestEffort either, so open to suggestions.

I'm terrible at naming things, so I'll go with it unless you have other ideas ;)

> I would love a PR, if you get the time the time for it, let me know.

I'll try to make it in the upcoming days.

**Comment by rehanvdm** [comment]
Sounds good, thanks.
